---
- name: Install and configure nginx
  hosts: all
  become: yes
  vars:
      nginx_package: 'nginx'
  tasks:
      - name: Install nginx
        package:
            name: '{{ nginx_package }}'
            state: present

      - name: Configure nginx
        template:
            src: nginx.conf.j2
            dest: /etc/nginx/nginx.conf
            mode: '0644'
        notify: restart nginx

      - name: Enable and start nginx
        service:
            name: nginx
            state: started
            enabled: yes

  handlers:
      - name: restart nginx
        service:
            name: nginx
            state: restarted
